In [2]:
import pandas as pd
import numpy as np

In [69]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
n = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
n[0,1]

np.int64(2)

In [11]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
n[:,1]

array([2, 5, 8])

In [13]:
n[:0]

array([], shape=(0, 3), dtype=int64)

In [14]:
n[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
n[: , 0]

array([1, 4, 7])

In [16]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [17]:
 pd.__version__

'3.0.6'

In [60]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [61]:
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

In [22]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [24]:
df.head(n=2)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3

In [25]:
df.model_year

0       2006
1       2008
2       1996
3       1989
4       1994
        ...
9995    2005
9996    1993
9997    2014
9998    2004
9999    2011
Name: model_year, Length: 10000, dtype: int64

In [31]:
df[['model_year', 'origin']]

      model_year  origin
0           2006  Europe
1           2008  Europe
2           1996    Asia
3           1989  Europe
4           1994     USA
...          ...     ...
9995        2005     USA
9996        1993    Asia
9997        2014     USA
9998        2004     USA
9999        2011     USA

[10000 rows x 2 columns]

In [35]:
df.fuel_type.unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [36]:
df.fuel_efficiency_mpg.max()

np.float64(41.2)

In [70]:
df.horsepower.median()

np.float64(254.0)

In [38]:
df.vehicle_weight.sum()

np.int64(42867540)

In [64]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [59]:
df.horsepower.median()

np.float64(252.0)

In [42]:
df.horsepower.mode()

0    252.0
Name: horsepower, dtype: float64

In [66]:
df['horsepower'] = df['horsepower'].fillna(252)

In [67]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower               0
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [78]:
df[df['origin'] =='Asia'][['vehicle_weight' , 'horsepower']].head(7)

    vehicle_weight  horsepower
2             4240       267.0
6             4310       250.0
8             4230       251.0
10            4420         NaN
15            3950       226.0
16            4750       234.0
22            4450       246.0