In [145]:
import pandas as pd
import numpy as np

from numpy.linalg import inv

In [146]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [147]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [148]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [149]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [150]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [151]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [152]:
n = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [153]:
n[0,1]

np.int64(2)

In [154]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [155]:
n[:,1]

array([2, 5, 8])

In [156]:
n[:0]

array([], shape=(0, 3), dtype=int64)

In [157]:
n[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [158]:
n[: , 0]

array([1, 4, 7])

In [159]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [160]:
 pd.__version__

'3.0.6'

In [161]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [162]:
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

In [163]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [164]:
df.head(n=2)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3

In [165]:
df.model_year

0       2006
1       2008
2       1996
3       1989
4       1994
        ...
9995    2005
9996    1993
9997    2014
9998    2004
9999    2011
Name: model_year, Length: 10000, dtype: int64

In [166]:
df[['model_year', 'origin']]

      model_year  origin
0           2006  Europe
1           2008  Europe
2           1996    Asia
3           1989  Europe
4           1994     USA
...          ...     ...
9995        2005     USA
9996        1993    Asia
9997        2014     USA
9998        2004     USA
9999        2011     USA

[10000 rows x 2 columns]

In [167]:
df.fuel_type.unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [168]:
df.fuel_efficiency_mpg.max()

np.float64(41.2)

In [169]:
df.horsepower.median()

np.float64(254.0)

In [170]:
df.vehicle_weight.sum()

np.int64(42867540)

In [171]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [172]:
df.horsepower.median()

np.float64(254.0)

In [173]:
df.horsepower.mode()

0    252.0
Name: horsepower, dtype: float64

In [174]:
df['horsepower'] = df['horsepower'].fillna(252)

In [175]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower               0
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [176]:
df.iloc[:7]

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
5,2007,USA,Hybrid,Front-wheel drive,2,2290,6,266.0,4260,18.8,31.2
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8

In [177]:
dfx= df[df['origin'] =='Asia'][['vehicle_weight' , 'horsepower']].iloc[:7]

In [178]:
dfx

    vehicle_weight  horsepower
2             4240       267.0
6             4310       250.0
8             4230       251.0
10            4420       252.0
15            3950       226.0
16            4750       234.0
22            4450       246.0

In [179]:
dfy = df[df['origin'] =='Asia'][['vehicle_weight' , 'model_year']].head(7)

In [180]:
dfy

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [181]:
X = pd.DataFrame(dfy).to_numpy()

In [182]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [183]:
XT = X.transpose()

In [184]:
XT

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [185]:
XTX  = np.matmul(XT, X )

In [186]:
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [187]:
XTXI = inv(XTX)

In [188]:
XTXI

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [189]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [190]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [191]:
ores = np.matmul(XTXI, XT )

In [192]:
ores

array([[-2.50082897e-04, -1.65786806e-05, -2.86196661e-04,
         3.99964853e-04, -1.18162927e-03,  1.10298508e-03,
         2.25354894e-04],
       [ 6.12974614e-04,  1.06954785e-04,  6.91249245e-04,
        -7.95968736e-04,  2.63152339e-03, -2.31749941e-03,
        -4.16221392e-04]])

In [193]:
tres = np.matmul(ores,y)

In [194]:
tres

array([0.13644777, 0.2327492 ])

In [195]:
tres.sum()

np.float64(0.36919696904925486)